"use client";

// CONTACT HUNTER — the screen.
//
// THE ONE THING THIS PAGE HAS TO GET RIGHT. Every contact database in this
// category shows a green tick beside an address that was generated by a script
// and never published anywhere. That single design decision is what turns a
// contact tool into a bounce machine and its owner into a spammer.
//
// So the provenance badge is not a detail; it is the loudest element beside
// every address, and CONFIRMED and INFERRED are rendered in different colours
// with different words. The inferred row also carries the reason it cannot be
// activated, in the same place the confirmed row carries its source URL. A user
// should not have to know the difference to be protected by it.
//
// The demo deliberately shows the SAME PERSON twice — once with the address the
// company published, once with the one we worked out — because the pair is the
// whole argument.

import { useCallback, useEffect, useState } from "react";
import { PageHeader, Pill } from "@/components/ui";
import { AlertTriangle, Ban, CheckCircle2, FileSearch, Loader2, PhoneCall, ShieldCheck, Sparkles } from "lucide-react";
import { authedFetch } from "@/frontend/api-client";
import {
  READINESS_WEIGHTS, PROHIBITED_CATEGORIES,
  type Readiness, type PatternFinding, type ContactPoint,
  type EmploymentFinding, type PhoneFinding, type SourceVerdict, type Refusal,
} from "@/shared/contact-hunter";

type Demo = {
  pattern: PatternFinding;
  thinPattern: PatternFinding;
  candidate: ContactPoint | null;
  candidateWhy: string;
  employment: EmploymentFinding;
  conflicted: EmploymentFinding;
  phone: PhoneFinding;
  unverifiedPhone: PhoneFinding;
  readyContact: Readiness;
  inferredContact: Readiness | null;
  intake: { ok: boolean; refusals: Refusal[] };
  sourceQuality: SourceVerdict[];
  gate: { allowed: boolean; blockers: string[] };
};

type Doctrine = {
  doctrine: string;
  provenance: Record<string, string>;
  reuses: Record<string, string>;
  demo: Demo;
};

function Provenance({ p }: { p: ContactPoint["provenance"] }) {
  const map = {
    confirmed: { label: "CONFIRMED", tone: "border-emerald-500/40 bg-emerald-500/10 text-emerald-300" },
    inferred: { label: "INFERRED — published nowhere", tone: "border-amber-500/40 bg-amber-500/10 text-amber-300" },
    provider: { label: "FROM A PROVIDER", tone: "border-sky-500/40 bg-sky-500/10 text-sky-300" },
  } as const;
  const m = map[p];
  return <span className={`rounded border px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wide ${m.tone}`}>{m.label}</span>;
}

function ScoreCard({ title, r, provenance }: { title: string; r: Readiness; provenance: ContactPoint["provenance"] }) {
  const blocked = r.activation === "BLOCKED";
  const ready = r.activation === "READY";
  return (
    <div className={`rounded-xl border p-4 ${blocked ? "border-rose-500/25 bg-rose-500/[0.05]" : ready ? "border-emerald-500/25 bg-emerald-500/[0.05]" : "border-white/10 bg-ink-900/50"}`}>
      <div className="flex flex-wrap items-center gap-2">
        <span className="text-sm font-bold text-white">{title}</span>
        <Provenance p={provenance} />
        <span className="ml-auto text-lg font-bold text-white">{r.score}</span>
        <Pill>{r.activation.replace(/_/g, " ")}</Pill>
      </div>
      <div className="mt-2 flex flex-wrap gap-1">
        {READINESS_WEIGHTS.map((w) => (
          <span key={w.key} className="rounded border border-white/10 px-1.5 py-0.5 text-[10px] text-slate-400">
            {w.label} {r.factors[w.key]}
          </span>
        ))}
      </div>
      {r.reasons.map((x) => <p key={x} className="mt-1.5 text-xs leading-relaxed text-slate-400">✓ {x}</p>)}
      {r.restrictions.map((x) => <p key={x} className="mt-1.5 text-xs leading-relaxed text-amber-200/90">— {x}</p>)}
      {r.blocks.map((x) => (
        <p key={x} className="mt-1.5 flex items-start gap-1.5 text-xs leading-relaxed text-rose-200">
          <Ban className="mt-0.5 h-3.5 w-3.5 shrink-0" /> {x}
        </p>
      ))}
    </div>
  );
}

export default function ContactHunterPage() {
  const [data, setData] = useState<Doctrine | null>(null);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    try {
      const res = await authedFetch("/api/contact-hunter");
      const d = await res.json().catch(() => ({}));
      if (!res.ok) { setError(d.error || "Could not read the engine."); return; }
      setData(d as Doctrine);
    } catch { setError("Network error."); }
  }, []);
  useEffect(() => { void load(); }, [load]);

  if (error) return <div className="p-6"><p className="rounded-lg border border-rose-500/25 bg-rose-500/[0.06] p-4 text-sm text-rose-200">{error}</p></div>;
  if (!data) return <div className="flex items-center gap-2 p-6 text-sm text-slate-400"><Loader2 className="h-4 w-4 animate-spin" /> Loading…</div>;

  const d = data.demo;

  return (
    <div className="space-y-6 p-4 sm:p-6">
      <PageHeader
        title="Contact Hunter"
        subtitle="Find the right business. Find the right decision-maker. Verify the route. Start the conversation — and know, for every value on the screen, how we came to hold it."
      />

      <p className="rounded-xl border border-white/10 bg-ink-900/50 p-4 text-sm leading-relaxed text-slate-300">{data.doctrine}</p>

      {/* THE PAIR. Same person, same company, two addresses — one published, one
          worked out. This is the argument the whole engine rests on. */}
      <section className="card p-5">
        <h2 className="flex items-center gap-2 font-display text-base font-bold text-white">
          <Sparkles className="h-4 w-4 text-emerald-400" /> The same person, two addresses
        </h2>
        <p className="mt-1 text-xs leading-relaxed text-slate-400">
          Every tool in this category shows a green tick beside an address a script generated and
          nobody ever published. Here they are side by side, scored by the same function.
        </p>
        <div className="mt-3 grid gap-3 lg:grid-cols-2">
          <ScoreCard title="procurement@exampleconstruction.co.uk" r={d.readyContact} provenance="confirmed" />
          {d.inferredContact && d.candidate && (
            <ScoreCard title={d.candidate.value} r={d.inferredContact} provenance="inferred" />
          )}
        </div>
        <p className="mt-3 rounded-lg border border-amber-500/25 bg-amber-500/[0.06] p-3 text-xs leading-relaxed text-amber-100">
          {d.candidateWhy}
        </p>
      </section>

      {/* The pattern, and its refusal on a thin sample. */}
      <section className="card p-5">
        <h2 className="flex items-center gap-2 font-display text-base font-bold text-white">
          <FileSearch className="h-4 w-4 text-emerald-400" /> The firm&rsquo;s email convention
        </h2>
        <div className="mt-3 grid gap-3 sm:grid-cols-2">
          <div className="rounded-lg border border-white/10 bg-ink-950/40 p-3">
            <p className="text-sm font-bold text-white">{d.pattern.pattern ?? "No pattern"}</p>
            <p className="mt-1 text-xs leading-relaxed text-slate-400">{d.pattern.why}</p>
          </div>
          <div className="rounded-lg border border-amber-500/25 bg-amber-500/[0.05] p-3">
            <p className="text-sm font-bold text-amber-200">Refused on a thin sample</p>
            <p className="mt-1 text-xs leading-relaxed text-amber-100/90">{d.thinPattern.why}</p>
          </div>
        </div>
      </section>

      {/* Employment: current, and the conflict that goes to a person. */}
      <section className="card p-5">
        <h2 className="font-display text-base font-bold text-white">Is the job title still true?</h2>
        <div className="mt-3 grid gap-3 sm:grid-cols-2">
          <div className="rounded-lg border border-white/10 bg-ink-950/40 p-3">
            <p className="text-sm font-bold text-white">{d.employment.jobTitle ?? "—"} <span className="text-xs font-normal text-slate-500">{d.employment.confidence}</span></p>
            <p className="mt-1 text-xs leading-relaxed text-slate-400">{d.employment.why}</p>
          </div>
          <div className="rounded-lg border border-rose-500/25 bg-rose-500/[0.05] p-3">
            <p className="flex items-center gap-1.5 text-sm font-bold text-rose-200"><AlertTriangle className="h-3.5 w-3.5" /> Conflicting</p>
            <p className="mt-1 text-xs leading-relaxed text-rose-100/90">{d.conflicted.why}</p>
          </div>
        </div>
      </section>

      {/* Phone: a format is not a verification. */}
      <section className="card p-5">
        <h2 className="flex items-center gap-2 font-display text-base font-bold text-white">
          <PhoneCall className="h-4 w-4 text-emerald-400" /> Numbers
        </h2>
        <div className="mt-3 grid gap-3 sm:grid-cols-2">
          {[d.phone, d.unverifiedPhone].map((p, i) => (
            <div key={i} className="rounded-lg border border-white/10 bg-ink-950/40 p-3">
              <p className="text-sm font-bold text-white">{p.e164 ?? "—"} <span className="text-xs font-normal text-slate-400">{p.status.replace(/_/g, " ")}</span></p>
              <p className="mt-1 text-xs leading-relaxed text-slate-400">{p.why}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Sources that turn themselves off. */}
      <section className="card p-5">
        <h2 className="font-display text-base font-bold text-white">Where the data came from, and how it performed</h2>
        <div className="mt-3 space-y-2">
          {d.sourceQuality.map((s) => (
            <div key={s.sourceDomain} className={`rounded-lg border p-3 ${s.enabled ? "border-white/10 bg-ink-950/40" : "border-rose-500/25 bg-rose-500/[0.05]"}`}>
              <div className="flex flex-wrap items-center gap-2">
                <span className="text-sm font-semibold text-white">{s.sourceDomain}</span>
                <Pill>{s.enabled ? "enabled" : "disabled"}</Pill>
                {s.bounceRate !== null && <span className="text-[11px] text-slate-500">bounce {(s.bounceRate * 100).toFixed(1)}% · complaints {((s.complaintRate ?? 0) * 100).toFixed(2)}% · wrong number {((s.wrongNumberRate ?? 0) * 100).toFixed(1)}%</span>}
              </div>
              <p className="mt-1 text-xs leading-relaxed text-slate-400">{s.why}</p>
            </div>
          ))}
        </div>
      </section>

      {/* The refusals. */}
      <section className="card p-5">
        <h2 className="flex items-center gap-2 font-display text-base font-bold text-white">
          <ShieldCheck className="h-4 w-4 text-emerald-400" /> What is refused at the door
        </h2>
        <p className="mt-2 text-xs leading-relaxed text-slate-400">
          These field names bounce the whole request, on every action, before anything is read or
          stored: <span className="text-slate-300">{PROHIBITED_CATEGORIES.join(", ")}</span>.
        </p>
        {d.intake.refusals.length > 0 && (
          <div className="mt-3 space-y-1.5">
            {d.intake.refusals.map((r) => (
              <p key={r.field} className="flex items-start gap-2 rounded-lg border border-rose-500/25 bg-rose-500/[0.06] p-2.5 text-xs leading-relaxed text-rose-200">
                <Ban className="mt-0.5 h-3.5 w-3.5 shrink-0" /> <span><span className="font-mono">{r.field}</span> — {r.why}</span>
              </p>
            ))}
          </div>
        )}
        <div className={`mt-3 rounded-lg border p-3 ${d.gate.allowed ? "border-emerald-500/25 bg-emerald-500/[0.06]" : "border-amber-500/25 bg-amber-500/[0.06]"}`}>
          <p className="flex items-center gap-1.5 text-sm font-semibold text-white">
            {d.gate.allowed ? <CheckCircle2 className="h-4 w-4 text-emerald-400" /> : <AlertTriangle className="h-4 w-4 text-amber-400" />}
            Activation gate: {d.gate.allowed ? "clear" : "blocked"}
          </p>
          {d.gate.blockers.map((b) => <p key={b} className="mt-1 text-xs leading-relaxed text-amber-100/90">{b}</p>)}
          <p className="mt-2 text-[11px] leading-relaxed text-slate-500">
            Checked before preview, before export and before send — three times, because a list that
            was compliant when it was built is not necessarily compliant when it is used.
          </p>
        </div>
      </section>

      {/* What it reuses, stated on the page — a claim anybody can go and check. */}
      <section className="card p-5">
        <h2 className="font-display text-base font-bold text-white">What this is built on</h2>
        <ul className="mt-2 space-y-1.5">
          {Object.entries(data.reuses).map(([k, v]) => (
            <li key={k} className="text-xs leading-relaxed text-slate-400">
              <span className="font-mono text-slate-300">{k}</span> — {v}
            </li>
          ))}
        </ul>
      </section>
    </div>
  );
}
