import { NextRequest, NextResponse } from "next/server";
import { emailConfigured, emailIsConfigured, filterList, sendEmail, sendEmailBatch, lastBatchMode, validateAttachments, type EmailAttachment } from "@/backend/email";
import { requireAuth, rateLimit, clientKey } from "@/backend/guard";
import { resolveBrandAccess } from "@/backend/brand-access";
import { replyAddressFor, replyVerdict } from "@/backend/reply-routing";
import { sendFailureOf, publicSendFailure, operatorFix, isRecipientRejection, redactSmtpLine, readSmtpRefusal, type SendFailure } from "@/shared/send-failure";
import { hasScope } from "@/shared/roles";

// M-34 email engine API.
// POST { action: "validate", emails: string[] }  → hygiene verdicts
// POST { action: "preview", brandId, subject, html | templateId }
//                                               → what really arrives, before it does
// POST { action: "send", to, subject, html }     → filtered, then sent
// GET                                            → engine status
export const runtime = "nodejs";
export const dynamic = "force-dynamic";
// A campaign is a SERIAL loop of SMTP sends, each of which can take seconds and
// is allowed up to 15 before it times out. Without a reserved budget the
// platform default kills the function part-way through — the customer sees
// "Request failed" with no JSON at all, and worse, the sends that DID go out are
// never counted, so a retry mails those people twice.
export const maxDuration = 60;

// Stop sending with time to spare, so the response is written by US rather than
// the function being killed. What went out is then reported honestly and counted
// against the warm-up allowance, and the rest is picked up by the next run.
const SEND_BUDGET_MS = Number(process.env.EMAIL_SEND_BUDGET_MS || 45_000);

export async function POST(req: NextRequest) {
  const rl = rateLimit(clientKey(req, "email"), 30, 60_000, Date.now());
  if (!rl.ok) return NextResponse.json({ error: "Rate limit exceeded" }, { status: 429, headers: { "Retry-After": String(rl.retryAfterSec) } });

  let body: Record<string, unknown> = {};
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  if (body.action === "validate") {
    const emails = Array.isArray(body.emails) ? body.emails.map(String) : [];
    if (!emails.length) {
      return NextResponse.json({ error: "emails[] required" }, { status: 400 });
    }
    const { sendable, filtered } = filterList(emails.slice(0, 1000));
    return NextResponse.json({
      total: emails.length,
      sendableCount: sendable.length,
      filteredCount: filtered.length,
      sendable,
      filtered,
    });
  }

  // PREVIEW — the same content, through the same pipeline, before it goes.
  //
  // Whatever the source (typed by hand, generated by the writer, or a saved
  // template) it arrives here as subject + html, so one action serves all
  // three and none of them can drift from the others. Reads only: no send, no
  // ACUs, no provider call.
  // WHERE WILL A REPLY GO? Answered with a real MX lookup before the send, not
  // discovered by a customer whose campaign got no replies for a month.
  if (body.action === "reply-check") {
    const rl = rateLimit(clientKey(req, "reply-check"), 60, 60_000, Date.now());
    if (!rl.ok) return NextResponse.json({ error: "Rate limit exceeded" }, { status: 429, headers: { "Retry-After": String(rl.retryAfterSec) } });
    const brandId = typeof body.brandId === "string" ? body.brandId.trim() : "";
    if (!brandId) return NextResponse.json({ error: "brandId required" }, { status: 400 });
    const access = await resolveBrandAccess(req, brandId);
    if (!access.ok) return NextResponse.json({ error: access.error }, { status: access.status });
    const verdict = await replyVerdict({
      brandId,
      replyTo: typeof body.replyTo === "string" ? body.replyTo : "",
      fromEmail: typeof body.fromEmail === "string" ? body.fromEmail : "",
    });
    return NextResponse.json({ ...verdict, brandReplyAddress: replyAddressFor(brandId) });
  }

  if (body.action === "preview") {
    const rl = rateLimit(clientKey(req, "email-preview"), 60, 60_000, Date.now());
    if (!rl.ok) return NextResponse.json({ error: "Rate limit exceeded" }, { status: 429, headers: { "Retry-After": String(rl.retryAfterSec) } });

    const brandId = typeof body.brandId === "string" ? body.brandId.trim() : "";
    if (!brandId) return NextResponse.json({ error: "brandId required" }, { status: 400 });
    // A preview renders real contacts from a real list, so it needs the same
    // ownership proof the send does.
    const access = await resolveBrandAccess(req, brandId);
    if (!access.ok) return NextResponse.json({ error: access.error }, { status: access.status });

    let subject = typeof body.subject === "string" ? body.subject : "";
    let html = typeof body.html === "string" ? body.html : "";
    let source: "written" | "ai" | "template" =
      body.source === "ai" || body.source === "template" ? body.source : "written";

    // A saved template supplies both, exactly as it does on the send path.
    const templateId = typeof body.templateId === "string" ? body.templateId.trim() : "";
    if (templateId) {
      const { getTemplate } = await import("@/backend/email-templates");
      const tpl = await getTemplate(brandId, templateId);
      if (!tpl) return NextResponse.json({ error: "Template not found for this brand" }, { status: 404 });
      subject = tpl.subject; html = tpl.html; source = "template";
    }
    if (!subject && !html) {
      return NextResponse.json({ error: "Nothing to preview — supply subject + html, or a templateId." }, { status: 400 });
    }

    const { listContacts } = await import("@/backend/contacts");
    const { buildEmailPreview } = await import("@/backend/email-preview");
    const preview = await buildEmailPreview({
      brandId, subject, html, source,
      brandName: typeof body.business === "string" ? body.business : "",
      contacts: await listContacts(brandId),
      campaign: typeof body.campaign === "string" ? body.campaign : "",
      statusFilter: typeof body.statusFilter === "string" ? body.statusFilter : "",
      // THE SAME SELECTION THE SEND WILL APPLY. Without it this panel previewed
      // a different audience from the one that would receive the campaign —
      // which is the one thing a preview must never do.
      groups: Array.isArray(body.groups)
        ? body.groups.filter((g): g is string => typeof g === "string" && g.trim().length > 0)
        : [],
      samples: Number(body.samples) || 3,
    });
    return NextResponse.json(preview);
  }

  if (body.action === "send") {
    // Real send — MUST be authenticated. Unauthenticated send would turn the
    // platform's authenticated sending domain into an open phishing relay.
    const auth = await requireAuth(req);
    if (!auth.ok) return NextResponse.json({ error: auth.error }, { status: auth.status });
    const { to, subject, html } = body as { to?: string; subject?: string; html?: string };
    const single = (Array.isArray(body.attachments) ? body.attachments : []) as EmailAttachment[];
    const singleCheck = validateAttachments(single);
    if (!singleCheck.ok) return NextResponse.json({ error: singleCheck.error }, { status: 400 });
    if (!to || !subject || !html) {
      return NextResponse.json({ error: "to, subject and html required" }, { status: 400 });
    }
    const result = await sendEmail({ to, subject, html, transactional: true, attachments: single.length ? single : undefined });
    return NextResponse.json(result, { status: result.ok ? 200 : 422 });
  }

  // Real BULK campaign send to a brand's Customer Vault (the Brevo-style blast).
  // Consent-gated + hygiene-filtered + suppression-aware; brand-ownership checked;
  // capped + throttled so reputation never breaks. POST { action:"send_campaign",
  // brandId, subject, html, test?, limit? }
  if (body.action === "send_campaign") {
    const rl = rateLimit(clientKey(req, "email-campaign"), 6, 60_000, Date.now());
    if (!rl.ok) return NextResponse.json({ error: "Rate limit exceeded — wait a moment." }, { status: 429, headers: { "Retry-After": String(rl.retryAfterSec) } });

    const brandId = typeof body.brandId === "string" ? body.brandId.trim() : "";
    if (!brandId) return NextResponse.json({ error: "brandId required" }, { status: 400 });
    const access = await resolveBrandAccess(req, brandId);
    if (!access.ok) return NextResponse.json({ error: access.error }, { status: access.status });

    // Attachments (documents/images) — validated ONCE before the send loop so a
    // bad file fails fast instead of part-way through a campaign.
    const attachments = (Array.isArray(body.attachments) ? body.attachments : []) as EmailAttachment[];
    const attCheck = validateAttachments(attachments);
    if (!attCheck.ok) return NextResponse.json({ error: attCheck.error }, { status: 400 });

    // Content comes from a saved template (personalised per contact) OR a raw
    // subject+html. A templateId wins and supplies both.
    let subject = typeof body.subject === "string" ? body.subject : "";
    let html = typeof body.html === "string" ? body.html : "";
    const templateId = typeof body.templateId === "string" ? body.templateId.trim() : "";
    if (templateId) {
      const { getTemplate } = await import("@/backend/email-templates");
      const tpl = await getTemplate(brandId, templateId);
      if (!tpl) return NextResponse.json({ error: "Template not found for this brand" }, { status: 404 });
      subject = tpl.subject; html = tpl.html;
    }
    if (!subject || !html) return NextResponse.json({ error: "subject and html required (or a valid templateId)" }, { status: 400 });

    const brandName = typeof body.business === "string" ? body.business : "";
    const { mergeTemplate } = await import("@/backend/email-templates");
    const { listContacts } = await import("@/backend/contacts");
    const contacts = await listContacts(brandId);
    // Optional status filter (prospect lists): "contacted" | "new" | etc.
    const statusFilter = typeof body.statusFilter === "string" ? body.statusFilter.trim().toLowerCase() : "";
    const byStatus = statusFilter ? contacts.filter((c) => (c.status || "").toLowerCase() === statusFilter) : contacts;

    // NAMED GROUPS — send to a list rather than to the whole vault.
    //
    // An EMPTY selection is everyone, so every campaign written before groups
    // existed behaves exactly as it did. Choosing groups is opting in to
    // narrowing, and `UNGROUPED` is a legitimate choice: newsletter signups and
    // audit leads arrive with no label and are often the first people worth
    // mailing.
    //
    // Applied AFTER the status filter and before eligibility, so the two can be
    // combined and the "nothing matched" message below can still tell the
    // customer which of the two emptied the list.
    const groupFilter = Array.isArray(body.groups)
      ? body.groups.filter((g): g is string => typeof g === "string" && g.trim().length > 0)
      : [];
    const { selectByGroups, UNGROUPED } = await import("@/shared/contact-groups");
    const pool = groupFilter.length ? selectByGroups(byStatus, groupFilter) : byStatus;

    if (groupFilter.length && pool.length === 0) {
      const named = groupFilter.map((g) => (g === UNGROUPED ? "not in any group" : `"${g}"`)).join(", ");
      return NextResponse.json({
        error: `No contacts are in ${named}${statusFilter ? ` with status "${statusFilter}"` : ""}, so there is nobody to send to. Nothing was sent and nothing was charged.`,
        sent: 0, attempted: 0, failed: 0, sendable: 0, consented: 0, remaining: 0,
        matched: 0, groups: groupFilter, mode: emailConfigured ? "live" : "demo", note: "",
      }, { status: 400 });
    }
    // Eligibility. Consent model matches the Customer Vault DISPLAY (which counts
    // a contact as consented unless it EXPLICITLY opted out, consent===false) so
    // "100% consented" in the vault and "sendable" here never disagree. Only an
    // explicit opt-out is excluded. For a status-targeted B2B prospect segment,
    // company addresses are eligible under legitimate interest. Either way an
    // EMAIL is mandatory — we can't send without one.
    const eligible = statusFilter
      ? pool.filter((c) => c.email)
      : pool.filter((c) => c.email && c.consent !== false);
    const consented = eligible.map((c) => c.email as string);
    if (consented.length === 0) {
      const haveEmail = pool.filter((c) => c.email).length;
      const optedOut = pool.filter((c) => c.email && c.consent === false).length;
      const msg = statusFilter
        ? `${pool.length} contact(s) match status "${statusFilter}", but ${haveEmail} have an email address. To email them the list needs an email column (or connect an enrichment provider). Nothing was sent.`
        : haveEmail === 0
          ? `Your vault has ${pool.length} contact(s) but none have an email address, so there's nothing to send to. Import a list that includes an email column.`
          : `All ${haveEmail} contact(s) with an email have opted out (${optedOut} suppressed), so nothing can be sent. Import contacts who haven't unsubscribed.`;
      return NextResponse.json({ error: msg, sent: 0, sendable: 0, matched: pool.length, withEmail: haveEmail }, { status: 400 });
    }
    // Hygiene pass (removes disposable/role/invalid before any send).
    const hygienic = filterList(consented).sendable.map((v) => v.email);
    // Persistent suppression: drop anyone the delivery-event feedback loop has
    // flagged (real bounces/complaints/unsubscribes), not just the in-memory set.
    const { suppressedEmails, injectTracking, recordEvent, unsubscribeUrl, trackingBaseFor } = await import("@/backend/email-events");
    // Resolved ONCE for the whole send. When this brand has published and
    // verified its own email.<domain> CNAME, every link and the unsubscribe URL
    // point at the brand's host instead of the shared platform one — the From
    // domain and the link domain finally match, and one customer's spam run can
    // no longer poison the click reputation of every other customer.
    const trackBase = await trackingBaseFor(brandId).catch(() => undefined);
    const suppressedSet = await suppressedEmails(brandId);
    const sendable = hygienic.filter((e) => !suppressedSet.has(e.toLowerCase()));
    // Cap per call: a test send (first 1) or a bounded batch so a runaway blast
    // can't torch the sending reputation. Larger lists send in repeated calls.
    const isTest = body.test === true;
    const cap = isTest ? 1 : Math.max(1, Math.min(500, Number(body.limit) || 250));

    // REPUTATION GUARDRAIL — the platform-level one.
    //
    // Warm-up caps VOLUME. This caps DAMAGE. MarketWar sends on shared
    // infrastructure, so reputation at Gmail and Microsoft attaches to the
    // sending domain rather than to the customer: one brand blasting a stale
    // list drags every other brand's mail toward the spam folder with it. Past
    // Google and Yahoo's published complaint limit, or an obviously dead list,
    // sending stops until it is cleaned.
    //
    // A test send of one message is exempt: it cannot move a rate, and blocking
    // the way a customer would verify their own fix helps nobody.
    if (!isTest) {
      const { brandEvents } = await import("@/backend/email-events");
      const { reputationVerdict, sendingBlocked } = await import("@/backend/deliverability");
      const ledger = await brandEvents(brandId).catch(() => []);
      const seenSent = new Set<string>(), seenBounce = new Set<string>(), seenComplaint = new Set<string>();
      for (const e of ledger) {
        const a = (e.email || "").toLowerCase();
        if (!a) continue;
        if (e.type === "sent") seenSent.add(a);
        else if (e.type === "bounce") seenBounce.add(a);
        else if (e.type === "complaint") seenComplaint.add(a);
      }
      const verdict = reputationVerdict({ sent: seenSent.size, bounces: seenBounce.size, complaints: seenComplaint.size });
      const gate = sendingBlocked(verdict);
      if (gate.blocked) {
        return NextResponse.json({
          error: gate.reason,
          sent: 0,
          reputation: verdict,
          blocked: true,
        }, { status: 409 });
      }
    }

    // WARM-UP GOVERNOR: enforce the ramping DAILY limit for this brand so a new
    // sending IP is never over-sent. Test sends bypass the block (but still count).
    const { getWarmup, recordWarmupSends } = await import("@/backend/email-warmup");
    const today = new Date().toISOString().slice(0, 10);
    const warm = await getWarmup(brandId, today);
    if (!isTest && warm.remaining <= 0) {
      // THE REASON TRAVELS WITH THE REFUSAL. The ceiling is no longer the
      // calendar's — it is the lower of the published ramp and what this brand's
      // own delivery record has earned — so "day 40, limit 100" is a correct
      // answer that looks like a bug without the sentence that explains it.
      return NextResponse.json({
        error: `Daily warm-up limit reached — ${warm.sentToday}/${warm.dailyCap} sent today (warm-up day ${warm.day}). ${warm.reason} Sending resumes tomorrow.`,
        sent: 0, attempted: 0, failed: 0, sendable: sendable.length, consented: consented.length, remaining: 0,
        dailyCap: warm.dailyCap, sentToday: warm.sentToday, day: warm.day,
        scheduleCap: warm.scheduleCap, earnedCap: warm.earnedCap, governedBy: warm.governedBy, verdict: warm.verdict,
        mode: emailConfigured ? "live" : "demo", note: "",
      }, { status: 429 });
    }
    const effectiveCap = isTest ? 1 : Math.min(cap, warm.remaining);
    const batch = sendable.slice(0, effectiveCap);
    const campaign = (typeof body.campaign === "string" ? body.campaign : subject).slice(0, 80);

    // Send AS the brand's own authenticated domain when set up: From + Reply-To on
    // the brand's address (so replies land in the brand's inbox), DKIM-signed with
    // that domain's key (the inbox key). Falls back to the platform sender when the
    // brand hasn't authenticated a domain yet.
    const { signingFor } = await import("@/backend/sending-domains");
    const fromEmail = typeof body.fromEmail === "string" && body.fromEmail.includes("@") ? body.fromEmail.trim() : "";
    const fromName = typeof body.fromName === "string" ? body.fromName.trim() : "";
    const fromDomain = fromEmail.split("@")[1] || "";
    const dkim = fromDomain ? (await signingFor(brandId, fromDomain)) ?? undefined : undefined;
    // WHO ACTUALLY SUBMITS THIS, versus who it claims to be from. Computed from
    // the node that will really log in, not from the environment variables —
    // MW_SENDING_POOL overrides those, and a report about the wrong credential
    // is how five weeks went by.
    let senderIdentity: { aligned: boolean; why: string } | null = null;
    try {
      const { pickNode, poolConfigured } = await import("@/backend/sending-pool");
      const { resolveSender } = await import("@/shared/sender-identity");
      const { bounceReturnPath } = await import("@/backend/email");
      const node = poolConfigured() ? pickNode(fromDomain, today) : null;
      if (fromEmail) {
        senderIdentity = resolveSender({ from: fromEmail, authUser: node?.user || "", bounce: bounceReturnPath() });
      }
    } catch { /* diagnostics must never take a send down */ }
    const fromHeader = fromEmail ? (fromName ? `${fromName} <${fromEmail}>` : fromEmail) : undefined;
    // Replies go here. Default to the From address, but let the sender point them
    // at their REAL inbox (e.g. their Gmail) so replies land where they read mail.
    const replyToRaw = typeof body.replyTo === "string" && body.replyTo.includes("@") ? body.replyTo.trim() : "";
    // THE ORDER IS UNCHANGED; WHAT CHANGED IS THAT THE MIDDLE TERM NOW TELLS THE
    // TRUTH. The reasoning that put it there was sound — nothing in the DNS this
    // platform asks for says where to deliver mail TO the customer's domain, so
    // a reply to hello@theircompany.com goes wherever their MX points, which may
    // be nowhere. The mistake was the remedy: the brand's address on our own
    // reply host was described as needing no DNS from them, when it needed DNS
    // from US that had never been published. `reply.marketwaros.com` has no MX,
    // so every prospect who hit Reply got a failure notice.
    //
    // `replyAddressFor` now returns "" until MW_REPLY_HOST is actually set, so
    // this falls through to the customer's own From address — which at least
    // reaches them whenever their domain accepts mail, and `reply-check` runs
    // the real MX lookup and says so before the send when it does not.
    const replyTo = replyToRaw || replyAddressFor(brandId) || fromEmail || undefined;

    // Per-recipient personalisation: look up each address's contact row and merge
    // {{ variables }} into the subject + body so every email is individual.
    const byEmail = new Map(eligible.map((c) => [(c.email as string).toLowerCase(), c]));

    let sent = 0, failed = 0;
    // WHY THEY FAILED, NOT JUST HOW MANY.
    //
    // REPORTED FROM THE LIVE PLATFORM: "0 sent · 104 failed · 104 attempted".
    // `sendEmail` returns a CATEGORY for every one of those 104 — a refused
    // password, a suppressed address, a paused account, a crash — and this route
    // counted them and threw the reason away. 104 identical failures with no
    // cause is the same boundary defect this codebase keeps producing, in the
    // one module the business depends on, multiplied by a hundred.
    //
    // Counting by category matters more than a sample: 104 `provider` failures
    // are ONE fault with one fix, while 104 `hygiene` failures are a list
    // problem and 104 `crashed` are ours. Identical counts, opposite actions.
    const byFailure = new Map<SendFailure, number>();
    // One representative server line per category — see the capture below.
    const firstDetail = new Map<SendFailure, string>();
    // Addresses nothing was even attempted for, because this deployment has no
    // sending server. Kept apart from `failed` so the two are never added up.
    let notConfigured = 0;
    let stoppedEarly = false;
    const sendDeadline = Date.now() + SEND_BUDGET_MS;
    const failures: string[] = [];

    // Personalise every message first — subject, body, tracking pixel, click
    // wrapping and a per-recipient one-click unsubscribe — then hand the whole
    // batch to ONE authenticated SMTP session.
    //
    // Opening a fresh connection, TLS handshake and AUTH per message cost about
    // a second and a half each before any content moved, which capped a run at
    // roughly 34 recipients inside the send budget: a 250-a-day allowance took
    // eight presses to spend. Reusing the session is also gentler on the
    // provider, which rate-limits connections far harder than messages.
    const prepared = batch.map((to) => {
      const contact = byEmail.get(to.toLowerCase());
      return {
        to,
        subject: mergeTemplate(subject, { contact, brand: brandName }),
        html: injectTracking(mergeTemplate(html, { contact, brand: brandName }), brandId, to, campaign, trackBase),
        listUnsubscribe: unsubscribeUrl(brandId, to, campaign, trackBase),
      };
    });

    let results: Awaited<ReturnType<typeof sendEmailBatch>> = [];
    try {
      results = await sendEmailBatch(prepared, {
        from: fromHeader, replyTo, dkim, brandId,
        attachments: attachments.length ? attachments : undefined,
        deadline: sendDeadline,
      });
    } catch {
      results = [];
    }

    for (let i = 0; i < prepared.length; i++) {
      const to = prepared[i].to;
      const r = results[i];
      // No result at all means the budget stopped the run before this address —
      // it was never attempted, so it stays sendable rather than counting failed.
      if (!r) { stoppedEarly = true; continue; }
      if (r.ok) {
        sent++;
        try { await recordEvent({ brandId, email: to, type: "sent", at: new Date().toISOString(), campaign }); } catch { /* stats best-effort */ }
      } else if (r.failure === "not_configured") {
        // NOT A FAILED ADDRESS. There is no sending server on this deployment,
        // so this address was never contacted and nothing about it is wrong.
        // Counting it as failed is what sent people off to clean a list that was
        // fine, and it must not reach the metrics or the warm-up ledger either —
        // an allowance spent on messages that do not exist is spent for real.
        notConfigured++;
      } else {
        failed++; if (failures.length < 10) failures.push(to);
        const cat = sendFailureOf(r.failure);
        byFailure.set(cat, (byFailure.get(cat) ?? 0) + 1);
        // KEEP THE SERVER'S OWN WORDS. `r.detail` holds the exact line the mail
        // server refused with, and until now it was read once by
        // `isRecipientRejection` on the line below and then dropped — so the
        // person waiting got our four-word paraphrase, "the mail server refused
        // the message", and never the sentence that says WHICH refusal it was.
        // "535 authentication failed", "550 SMTP is disabled for this account"
        // and "temporarily blocked after too many attempts" all wear that same
        // paraphrase and have three different fixes, none of them guessable from
        // it. One line per category is enough: the first is representative and a
        // hundred copies of it are not more informative.
        if (typeof r.detail === "string" && r.detail.trim() && !firstDetail.has(cat)) {
          firstDetail.set(cat, r.detail);
        }
        // SUPPRESS ONLY WHEN THE SERVER NAMED THE RECIPIENT.
        //
        // This used to be `/\b5\d\d\b/.test(r.detail)` — any 5xx anywhere in the
        // text. The SMTP server was refusing our PASSWORD, `535 5.7.8`, and 535
        // is a 5xx: 104 good prospects on one brand and 250 on another were
        // recorded as hard bounces and suppressed for ever because OUR credential
        // was wrong. The vault went from 104 sendable to 0, and the fabricated
        // bounce rate then had the deliverability agent telling the owner to buy
        // a list-cleaning service.
        //
        // A wrongful suppression is permanent and costs a customer; a retry costs
        // a fraction of a penny. `isRecipientRejection` therefore refuses unless
        // the server's words identify the mailbox.
        if (isRecipientRejection(r.detail) || r.failure === "hygiene") {
          try { await recordEvent({ brandId, email: to, type: "bounce", at: new Date().toISOString(), campaign }); } catch { /* best-effort */ }
        }
      }
    }
    // Count what actually went out against today's warm-up allowance.
    if (sent > 0) { try { await recordWarmupSends(brandId, today, sent); } catch { /* counter best-effort */ } }
    const dailyRemaining = Math.max(0, warm.remaining - sent);
    // `notConfigured` is NOT added in: nothing was attempted for those addresses.
    const attempted = sent + failed;
    // Anything the budget cut off is still sendable and must be counted as such,
    // or the customer thinks the campaign finished when most of it never went.
    const notReached = batch.length - attempted - notConfigured;
    const live = emailIsConfigured();

    // The dominant category, because that is the one fix that moves the number.
    const ranked = [...byFailure.entries()].sort((a, b) => b[1] - a[1]);
    const worst = ranked[0];
    // The refusal that goes on the screen, with the names taken out.
    // `redactSmtpLine` removes any mailbox, hostname and IP, so what is left is a
    // status code and a sentence the mail server wrote about itself — the
    // evidence with none of the identity, which is safe for the brand's own
    // owner to read about their own send. `readSmtpRefusal` adds what it means
    // ONLY when the words are specific enough to say; it returns "" otherwise,
    // because an invented reading is worse than none.
    const worstLine = worst ? redactSmtpLine(firstDetail.get(worst[0])) : "";
    const worstMeaning = worstLine ? readSmtpRefusal(firstDetail.get(worst[0])) : "";
    // The operator's remedy names environment variables and an internal
    // diagnostic — our infrastructure, not this brand's. A tenant gets the
    // sentence about their send; the person who can fix the deployment gets the
    // instruction. Read off the role already verified above rather than
    // re-verifying the token.
    const isOperator = Boolean(access.role && hasScope(access.role, "platform_admin"));
    const failureBreakdown = Object.fromEntries(ranked);

    return NextResponse.json({
      mode: live ? "live" : "demo",
      vaultTotal: contacts.length, consented: consented.length, sendable: sendable.length,
      attempted, sent, failed, failures,
      // WHY, in the same breath as HOW MANY.
      ...(worst ? {
        failureReason: worst[0],
        failureBreakdown,
        failureNote: `${worst[1]} of ${failed} failed because ${publicSendFailure(worst[0])}.`,
        ...(worstLine ? { serverSaid: worstLine } : {}),
        ...(worstMeaning ? { serverMeaning: worstMeaning } : {}),
        ...(isOperator ? { operatorFix: operatorFix(worst[0]) } : {}),
      } : {}),
      // Reported separately and never folded into `failed` — these addresses are
      // still perfectly sendable the moment a sending server exists.
      notConfigured,
      stoppedEarly, notReached,
      // Which path actually ran. Reported because the alternative is inferring it
      // from a throughput number, which is how a stale deploy and a real cap look
      // identical from the outside.
      sendMode: lastBatchMode,
      remaining: Math.max(0, sendable.length - attempted),
      dailyCap: warm.dailyCap, sentToday: warm.sentToday + sent, dailyRemaining, day: warm.day,
      authenticatedAs: dkim ? `${fromEmail} (DKIM-signed as ${dkim.domain})` : fromEmail ? `${fromEmail} (domain not yet authenticated — sign it in Sending Domains for inbox placement)` : "platform default sender",
      // ACCEPTED IS NOT DELIVERED, AND THE DIFFERENCE IS USUALLY ALIGNMENT.
      //
      // Reported live: "1 sent · 0 failed" and the message never arrived. The
      // screen said "DKIM-signed as kodajnn.com", which reads as fully
      // authenticated — while the account that submitted it was a mailbox on
      // ANOTHER domain, so the envelope sender is that other domain and, under
      // `aspf=s`, the SPF half of DMARC cannot align however correct the DNS is.
      // The whole pass then rests on the DKIM signature surviving every relay in
      // between. That is worth knowing BEFORE a campaign, not after it vanishes.
      ...(senderIdentity ? { senderAlignment: { aligned: senderIdentity.aligned, why: senderIdentity.why } } : {}),
      note: live
        ? `${stoppedEarly ? `Time ran out part-way through: ${sent} of ${batch.length} were sent and ${notReached} were not reached. Nobody was sent to twice — run again to continue from where it stopped. ` : ""}Sent ${sent} of ${attempted || batch.length}. ${worst ? `${worst[1]} failed because ${publicSendFailure(worst[0])}.${worstLine ? ` The server said: “${worstLine}”.` : ""}${worstMeaning ? ` ${worstMeaning}` : ""}${isOperator ? ` ${operatorFix(worst[0])}` : ""} ` : ""}${dailyRemaining > 0 && sendable.length - batch.length > 0 ? `Run again to send the next batch (${dailyRemaining} left in today's warm-up limit). ` : dailyRemaining <= 0 ? `That's today's warm-up limit (day ${warm.day}: ${warm.dailyCap}/day) — the rest sends tomorrow. ` : ""}Inbox placement depends on your domain's SPF/DKIM/DMARC + IP reputation.`
        : `Nothing was sent. This deployment has no sending server, so all ${notConfigured} ${notConfigured === 1 ? "address was" : "addresses were"} left uncontacted — none of them failed, and none of them was used up. Set MW_SENDING_POOL (or SMTP_HOST/SMTP_USER/SMTP_PASS), or RESEND_API_KEY, or SENDGRID_API_KEY, then run this again and they all still go.`,
    });
  }

  return NextResponse.json({ error: "Unknown action — use validate, send or send_campaign" }, { status: 400 });
}

// THE ENDPOINT SOMEBODY OPENS WHEN NOTHING IS ARRIVING.
//
// It read the frozen import-time constants, so it could not answer the one
// question worth asking here — "I set the variable, is it live NOW?" — and it
// never said what to do about a "demo" it reported. Both fixed: asked on demand,
// and it names the action.
export async function GET() {
  const { activeEmailProvider, emailIsConfigured: live } = await import("@/backend/email");
  const provider = activeEmailProvider();
  const configured = live();
  return NextResponse.json({
    engine: "M-34 AI Transactional Email Engine",
    mode: configured ? "live" : "demo",
    provider, // "smtp" | "resend" | "sendgrid" | "demo" — never a credential
    // Unambiguous, because "demo" has been read as "fine, it is simulating" by
    // everyone who has ever looked at it, including while real campaigns were
    // being reported as sent.
    sending: configured,
    willAnythingArrive: configured
      ? "Yes — a provider is configured. Delivery still depends on SPF/DKIM/DMARC and reputation."
      : "No. Nothing sent from this deployment reaches anybody, and every send is reported as not sent.",
    toGoLive: configured
      ? null
      : "Set MW_SENDING_POOL (or SMTP_HOST + SMTP_USER + SMTP_PASS), or RESEND_API_KEY, or SENDGRID_API_KEY, then redeploy and reopen this endpoint.",
    from: process.env.EMAIL_FROM || "MarketWar OS <os@notifications.marketwaros.com>",
    hygiene: ["syntax", "disposable-domain", "role-address", "suppression-ledger"],
    doctrine: "Inbox placement is earned: authentication + warm-up + consent + hygiene. Bounces are prevented pre-send and never repeated.",
  });
}
