"use client";

import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, Eye, Loader2, Mail, RefreshCcw, ShieldCheck, Smartphone } from "lucide-react";
import { authedFetch } from "@/frontend/api-client";
import CopyOut from "@/components/CopyOut";

// See it before two thousand people do.
//
// One panel for all three sources, on purpose. Hand-written, generated by the
// writer, or a saved template — they all reach the server as subject + html and
// come back through the same pipeline the send uses, so none of them can drift
// from the others or from what is delivered.
//
// It shows a REAL contact from the list, not a specimen "John Smith". A made-up
// contact has every field filled in, which is the one case that never goes
// wrong; the contact with no name is where "Hi {{ firstName }}" falls back to
// "Hi there", and that is the substitution worth seeing before it goes out.

export type PreviewCheck = { level: "blocker" | "warning"; message: string; where: "subject" | "body" | "list" };
export type PreviewSample = { to: string; name: string; subject: string; html: string; text: string; preheader: string };
export type EmailPreviewData = {
  source: "written" | "ai" | "template";
  recipients: number;
  samples: PreviewSample[];
  checks: PreviewCheck[];
  sendable: boolean;
  tokensUsed: string[];
  note: string;
  error?: string;
};

const SOURCE_LABEL: Record<EmailPreviewData["source"], string> = {
  written: "Written here",
  ai: "Generated",
  template: "Saved template",
};

export default function EmailPreview({
  brandId,
  subject,
  html,
  templateId,
  business,
  statusFilter,
  source = "written",
  onSendable,
}: {
  brandId: string;
  subject?: string;
  html?: string;
  templateId?: string;
  business?: string;
  statusFilter?: string;
  source?: EmailPreviewData["source"];
  /** Lets the parent gate its Send button on the same answer. */
  onSendable?: (sendable: boolean, blockers: number) => void;
}) {
  const [data, setData] = useState<EmailPreviewData | null>(null);
  const [busy, setBusy] = useState(false);
  const [i, setI] = useState(0);
  const [view, setView] = useState<"desktop" | "phone" | "text">("desktop");

  const load = useCallback(async () => {
    if (!brandId || (!templateId && !subject && !html)) return;
    setBusy(true);
    try {
      const res = await authedFetch("/api/email", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ action: "preview", brandId, subject, html, templateId, business, statusFilter, source }),
      });
      const d = (await res.json()) as EmailPreviewData;
      setData(d);
      setI(0);
      onSendable?.(Boolean(d.sendable), (d.checks || []).filter((c) => c.level === "blocker").length);
    } catch {
      setData({ source, recipients: 0, samples: [], checks: [], sendable: false, tokensUsed: [], note: "", error: "Could not reach the server for a preview." });
      onSendable?.(false, 1);
    } finally {
      setBusy(false);
    }
  }, [brandId, subject, html, templateId, business, statusFilter, source, onSendable]);

  // Re-preview when the content settles. Debounced, because every keystroke in
  // the editor would otherwise be a request.
  useEffect(() => {
    const t = setTimeout(load, 600);
    return () => clearTimeout(t);
  }, [load]);

  const blockers = (data?.checks || []).filter((c) => c.level === "blocker");
  const warnings = (data?.checks || []).filter((c) => c.level === "warning");
  const sample = data?.samples?.[i];

  return (
    <div className="card p-5">
      <div className="mb-1 flex flex-wrap items-center gap-2">
        <Eye className="h-4 w-4 text-emerald-400" />
        <h3 className="font-display text-sm font-bold text-white">Preview — what actually arrives</h3>
        <span className="rounded bg-white/[0.05] px-1.5 py-0.5 text-[10px] text-slate-300">{SOURCE_LABEL[data?.source ?? source]}</span>
        <button className="ml-auto inline-flex items-center gap-1 text-[11px] text-slate-400 hover:text-white" onClick={load} disabled={busy}>
          {busy ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <RefreshCcw className="h-3.5 w-3.5" />} Refresh
        </button>
      </div>
      <p className="mb-3 text-[11px] leading-relaxed text-slate-500">
        Merged for a real contact on this list, with the tracking and the unsubscribe line the send appends — not a
        mock-up of it.
      </p>

      {data?.error && <p className="rounded-md bg-rose-500/10 px-3 py-2 text-xs text-rose-300">{data.error}</p>}

      {/* Blockers first and loudest. These are the ones that go wrong for
          every single recipient, not just the awkward ones. */}
      {blockers.length > 0 && (
        <div className="mb-3 rounded-lg border border-rose-500/30 bg-rose-500/[0.06] p-3">
          <p className="mb-1.5 flex items-center gap-1.5 text-xs font-bold text-rose-200">
            <AlertTriangle className="h-3.5 w-3.5" /> {blockers.length} thing{blockers.length === 1 ? "" : "s"} that would go wrong for everyone
          </p>
          <ul className="space-y-1">
            {blockers.map((c, n) => (
              <li key={n} className="text-[11px] leading-relaxed text-rose-100/90">
                <span className="uppercase tracking-wide text-rose-300/70">{c.where}</span> — {c.message}
              </li>
            ))}
          </ul>
        </div>
      )}

      {warnings.length > 0 && (
        <div className="mb-3 rounded-lg border border-amber-500/25 bg-amber-500/[0.05] p-3">
          <ul className="space-y-1">
            {warnings.map((c, n) => (
              <li key={n} className="text-[11px] leading-relaxed text-amber-100/90">
                <span className="uppercase tracking-wide text-amber-300/70">{c.where}</span> — {c.message}
              </li>
            ))}
          </ul>
        </div>
      )}

      {data && blockers.length === 0 && data.recipients > 0 && (
        <p className="mb-3 flex items-center gap-1.5 rounded-md bg-emerald-500/[0.07] px-3 py-2 text-[11px] text-emerald-200">
          <ShieldCheck className="h-3.5 w-3.5 shrink-0" /> Nothing found that would go wrong. {data.recipients.toLocaleString()} recipient{data.recipients === 1 ? "" : "s"}.
        </p>
      )}

      {sample && (
        <>
          <div className="mb-2 flex flex-wrap items-center gap-1.5">
            {data!.samples.map((s, n) => (
              <button
                key={s.to + n}
                onClick={() => setI(n)}
                className={`rounded px-2 py-1 text-[10px] ${n === i ? "bg-white/[0.09] text-white" : "text-slate-400 hover:text-white"}`}
                title={s.name || "no name on this contact"}
              >
                {s.name || "(no name)"} · {s.to}
              </button>
            ))}
            <div className="ml-auto flex gap-1">
              {(["desktop", "phone", "text"] as const).map((v) => (
                <button
                  key={v}
                  onClick={() => setView(v)}
                  className={`rounded px-2 py-1 text-[10px] capitalize ${view === v ? "bg-white/[0.09] text-white" : "text-slate-400 hover:text-white"}`}
                >
                  {v === "phone" ? <Smartphone className="inline h-3 w-3" /> : v === "text" ? "Aa" : <Mail className="inline h-3 w-3" />} {v}
                </button>
              ))}
            </div>
          </div>

          {/* The inbox line: subject, then the grey preheader beside it. This is
              the whole of what most people read before deciding. */}
          <div className="mb-2 rounded-lg border border-white/[0.07] bg-ink-900/60 p-3">
            <p className="text-sm font-semibold text-white">{sample.subject || <span className="text-rose-300">(no subject)</span>}</p>
            <p className="mt-0.5 truncate text-xs text-slate-500">{sample.preheader || "(nothing to preview beside the subject)"}</p>
          </div>

          {/* TAKE IT AWAY. When sending is not configured on a deployment —
              the normal state until a domain is verified — copying the message
              out is the ONLY way this engine produces anything at all. A
              preview with no copy button is a feature that cannot be used and
              looks like one that works. */}
          <div className="mb-2 flex flex-wrap items-center gap-2">
            <CopyOut text={`Subject: ${sample.subject}\n\n${sample.text}`} filename="email.txt" label="Copy the message" />
            <CopyOut text={sample.html} filename="email.html" mime="text/html" label="Copy the HTML" compact />
            <span className="text-[11px] text-slate-500">Paste it straight into your own inbox and send it from there.</span>
          </div>

          <div className="overflow-x-auto rounded-lg border border-white/[0.07] bg-white">
            {view === "text" ? (
              <pre className="max-h-[520px] overflow-auto whitespace-pre-wrap p-4 text-[12px] leading-relaxed text-ink-950">{sample.text}</pre>
            ) : (
              // srcDoc, sandboxed: the message is the customer's own HTML and it
              // is rendered rather than described, but it must not be able to
              // run anything against the dashboard it is being shown inside.
              <iframe
                title="Email preview"
                sandbox=""
                srcDoc={sample.html}
                className="block h-[520px] border-0 bg-white"
                style={{ width: view === "phone" ? 390 : "100%", margin: view === "phone" ? "0 auto" : undefined }}
              />
            )}
          </div>
        </>
      )}

      {data?.note && <p className="mt-2 text-[10px] leading-relaxed text-slate-500">{data.note}</p>}
      {data && data.tokensUsed.length > 0 && (
        <p className="mt-1 text-[10px] text-slate-500">Personalised on: {data.tokensUsed.join(", ")}.</p>
      )}
    </div>
  );
}
