"use client";

// The Money Ledger (Money Machine Doctrine, Law 2 — Attribution Law).
// The retention engine: it prints MarketWar's receipts. Attributed revenue comes
// from the REAL per-brand results ledger (src/frontend/results-context) — never
// fabricated. MarketWar spend is the user's own figure (subscription + ACU
// top-ups), stored locally per brand, so ROI = revenue ÷ spend is honest and
// the user is always in control of the denominator.

import { useEffect, useMemo, useState } from "react";
import { PageHeader, Pill, StatCard } from "@/components/ui";
import { AreaChart } from "@/components/charts";
import { Receipt, TrendingUp, Users, Coins, Swords, Save } from "lucide-react";
import { useActiveBrand } from "@/frontend/brand-context";
import { useResults } from "@/frontend/results-context";

const money = (n: number) => `£${(n || 0).toLocaleString("en-GB", { maximumFractionDigits: 2 })}`;
const spendKey = (brandId: string) => `mw_spend_${brandId}`;

export default function MoneyLedgerPage() {
  const { activeBrand } = useActiveBrand();
  const { events, summary } = useResults();
  const [spend, setSpend] = useState<number>(0);
  const [spendInput, setSpendInput] = useState<string>("");
  const [saved, setSaved] = useState(false);

  // Load the brand's saved MarketWar cost (their own figure).
  useEffect(() => {
    if (!activeBrand || typeof window === "undefined") { setSpend(0); setSpendInput(""); return; }
    const raw = window.localStorage.getItem(spendKey(activeBrand.id));
    const val = raw ? Math.max(0, Number(raw) || 0) : 0;
    setSpend(val); setSpendInput(val ? String(val) : "");
  }, [activeBrand]);

  function saveSpend() {
    if (!activeBrand) return;
    const val = Math.max(0, Number(spendInput) || 0);
    setSpend(val);
    try { window.localStorage.setItem(spendKey(activeBrand.id), String(val)); } catch { /* private mode */ }
    setSaved(true); setTimeout(() => setSaved(false), 1800);
  }

  const revenue = summary.revenueGbp;
  const roi = spend > 0 ? revenue / spend : null;
  const revenuePerCustomer = summary.orders > 0 ? revenue / summary.orders : 0;

  // Attributed events, newest first — the receipts.
  const receipts = useMemo(
    () => [...events].filter((e) => e.type === "order" || e.type === "sale").sort((a, b) => (a.at < b.at ? 1 : -1)).slice(0, 30),
    [events],
  );

  const roiTone = roi == null ? "neutral" : roi >= 5 ? "good" : roi >= 1 ? "warn" : "bad";

  if (!activeBrand) {
    return (
      <div>
        <PageHeader kicker="Money Ledger" title="Your MarketWar receipts" subtitle="Add a brand to see the revenue MarketWar has generated for it and your ROI." />
        <div className="card border-emerald-500/20 p-10 text-center"><Receipt className="mx-auto mb-2 h-7 w-7 text-emerald-500/60" /><h2 className="font-display text-lg font-bold text-white">Pick or add a brand</h2></div>
      </div>
    );
  }

  return (
    <div>
      <PageHeader
        kicker="Money Ledger"
        title={`What MarketWar made for ${activeBrand.name}`}
        subtitle="Every figure here is real: attributed revenue from your own results ledger, and your own MarketWar cost. Nothing invented."
        actions={<Pill tone={roiTone === "good" ? "good" : roiTone === "bad" ? "bad" : "info"}>{roi == null ? "Add your cost to see ROI" : `${roi.toFixed(1)}x ROI`}</Pill>}
      />

      {/* The receipt line — Law 2 */}
      <div className={`mb-6 card p-5 ${roi != null && roi >= 5 ? "border-emerald-500/40 bg-emerald-500/[0.06]" : ""}`}>
        {revenue === 0 ? (
          <p className="text-sm text-slate-300">No attributed revenue yet. The moment a lead converts or you log a sale, this line becomes your receipt — and your ROI appears against your MarketWar cost.</p>
        ) : roi == null ? (
          <p className="text-sm text-slate-200"><span className="font-bold text-emerald-300">MarketWar has generated {money(revenue)}</span> for {activeBrand.name}. Enter your MarketWar cost below to see your ROI multiple.</p>
        ) : (
          <p className="text-base text-slate-200">
            <span className="font-bold text-emerald-300">MarketWar generated {money(revenue)}</span> for you. Your MarketWar cost was {money(spend)}.{" "}
            <span className={`font-bold ${roi >= 5 ? "text-emerald-300" : roi >= 1 ? "text-amber-300" : "text-rose-300"}`}>ROI: {roi.toFixed(1)}x.</span>
            {roi >= 5 && " You're in the ≥5x band — the machine is paying for itself many times over."}
          </p>
        )}
      </div>

      {/* North-Star Metrics (§8) */}
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
        <StatCard label="Attributed revenue" value={money(revenue)} tone={revenue > 0 ? "good" : "neutral"} sub="generated by MarketWar" />
        <StatCard label="ROI multiple" value={roi == null ? "—" : `${roi.toFixed(1)}x`} tone={roiTone === "good" ? "good" : roiTone === "bad" ? "bad" : "neutral"} sub={roi == null ? "add your cost" : "revenue ÷ cost"} />
        <StatCard label="New customers" value={`${summary.orders}`} tone={summary.orders > 0 ? "good" : "neutral"} sub="orders + sales" />
        <StatCard label="Revenue per customer" value={summary.orders > 0 ? money(revenuePerCustomer) : "—"} sub="multiplication effect" />
        <StatCard label="Territory share" value="—" sub="connect competitor tracking" />
      </div>

      {/* Your MarketWar cost (the honest denominator) */}
      <div className="mt-6 card p-5">
        <h2 className="mb-1 flex items-center gap-2 font-display text-sm font-bold text-white"><Coins className="h-4 w-4 text-emerald-400" /> Your MarketWar cost</h2>
        <p className="mb-3 text-xs text-slate-400">Enter your total MarketWar spend for the period (subscription + any ACU top-ups). This is your figure — we use it only to compute your ROI honestly.</p>
        <div className="flex flex-wrap items-center gap-2">
          <div className="flex items-center gap-2 rounded-lg border border-ink-700 bg-ink-900/70 px-3 py-2">
            <span className="text-sm text-slate-500">£</span>
            <input type="number" min={0} value={spendInput} onChange={(e) => setSpendInput(e.target.value)} placeholder="199" className="w-28 bg-transparent text-sm text-white outline-none" />
          </div>
          <button onClick={saveSpend} className="inline-flex items-center gap-1.5 rounded-lg bg-emerald-500 px-4 py-2 text-sm font-bold text-ink-950 hover:bg-emerald-400"><Save className="h-4 w-4" /> Save</button>
          {saved && <span className="text-xs font-semibold text-emerald-300">Saved.</span>}
        </div>
      </div>

      {/* Revenue over time */}
      {summary.byDay.length > 0 && (
        <div className="mt-6 card p-5">
          <h2 className="mb-3 flex items-center gap-2 font-display text-sm font-bold text-white"><TrendingUp className="h-4 w-4 text-emerald-400" /> Attributed revenue over time</h2>
          <AreaChart labels={summary.byDay.map((d) => d.day.slice(5))} series={[{ name: "Revenue", data: summary.byDay.map((d) => d.revenueGbp) }]} valuePrefix="£" height={200} />
        </div>
      )}

      {/* The receipts — every attributed sale */}
      <div className="mt-6 card p-5">
        <h2 className="mb-3 flex items-center gap-2 font-display text-sm font-bold text-white"><Receipt className="h-4 w-4 text-emerald-400" /> Receipts — attributed sales</h2>
        {receipts.length === 0 ? (
          <p className="text-sm text-slate-400">No sales attributed yet. Log a result or let a landing/checkout link convert — each one lands here, stamped with its source.</p>
        ) : (
          <div className="divide-y divide-white/[0.06]">
            {receipts.map((e) => (
              <div key={e.id} className="flex items-center justify-between gap-3 py-2.5 text-sm">
                <div>
                  <p className="font-semibold text-white">{money(e.amountGbp)} <span className="font-normal text-slate-500">· {e.source?.trim() || "Untagged"}</span></p>
                  {e.note && <p className="text-xs text-slate-500">{e.note}</p>}
                </div>
                <span className="text-xs text-slate-600">{new Date(e.at).toLocaleDateString("en-GB")}</span>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Per-source rollup — where the money came from */}
      {summary.bySource.length > 0 && (
        <div className="mt-6 card p-5">
          <h2 className="mb-3 flex items-center gap-2 font-display text-sm font-bold text-white"><Swords className="h-4 w-4 text-emerald-400" /> Where the money came from</h2>
          <div className="space-y-2">
            {summary.bySource.map((s) => (
              <div key={s.source} className="flex items-center justify-between rounded-lg border border-white/[0.06] bg-ink-900/50 p-3 text-sm">
                <span className="text-slate-200">{s.source} <span className="text-slate-500">· {s.orders} order{s.orders === 1 ? "" : "s"}, {s.leads} lead{s.leads === 1 ? "" : "s"}</span></span>
                <span className="font-bold text-emerald-300">{money(s.revenueGbp)}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      <p className="mt-6 flex items-center gap-1.5 text-xs text-slate-600"><Users className="h-3.5 w-3.5" /> Revenue is attributed from your own results ledger — real, per-brand, never fabricated. ROI uses the cost you entered.</p>
    </div>
  );
}
